apply plugin: 'com.android.application'

android {
    namespace "com.khaled.kuwaitradio"
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.khaled.kuwaitradio"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
